name: "VirtualBox controlvm"
description: "Run VBoxManage controlvm with custom arguments."

inputs:
  arguments:
    description: "Newline-separated arguments passed to 'VBoxManage controlvm'."
    required: false
    default: ""
  vboxmanage_path:
    description: "Path to VBoxManage.exe."
    required: false
    default: "C:\\Progra~1\\Oracle\\VirtualBox\\VBoxManage.exe"

runs:
  using: "composite"
  steps:
    - name: "Run VBoxManage controlvm"
      shell: "powershell"
      run: |
        $scriptPath = Join-Path '${{ github.action_path }}' '..\scripts\virtualbox\Run-VBoxManage.ps1'
        & $scriptPath -Subcommand 'controlvm' -Arguments '${{ inputs.arguments }}' -VBoxManagePath '${{ inputs.vboxmanage_path }}'
